### ISSUE TITLE
Can't compile on Linux Debian 11

### ISSUE THREAD

**Issue by domisphere-dev** [ilobilo/ilar#1]
I tried to compile ilar on my Debian 11 laptop but it doesn't work no matter what I try. I use g++ as a compiler and I also installed the boost_iostreams library

Because the error message is very long, I uploaded it to my server. [Here is the link to the error message ](https://cdn.platin-developmentstudios.de/files/error.txt)

**Comment by ilobilo** [comment]
Sorry for the late response @TheDomCraft
Could you try compiling it now?

**Comment by domisphere-dev** [comment]
Yes, please wait a bit

**Comment by domisphere-dev** [comment]
Compiling works now, thanks!

**Comment by ilobilo** [comment]
np
